blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using tinydns
    url: https://github.com/projectdiscovery/tinydns/discussions/categories/q-a
    about: Ask a question or request support for using tinydns

  - name: Share idea / feature to discuss for tinydns
    url: https://github.com/projectdiscovery/tinydns/discussions/categories/ideas
    about: Share idea / feature to discuss for tinydns

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication